"""empty message

Revision ID: 036e55bfd171
Revises: f42c552e0b22
Create Date: 2019-03-19 19:45:01.234337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036e55bfd171'
down_revision = 'f42c552e0b22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('cpf', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuarios', 'cpf')
    # ### end Alembic commands ###
