"""empty message

Revision ID: 362319faad60
Revises: b97fb81c0823
Create Date: 2019-03-25 21:53:54.681890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '362319faad60'
down_revision = 'b97fb81c0823'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pessoa')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pessoa',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
