"""empty message

Revision ID: 545e0fa8fb50
Revises: ef7b0eade933
Create Date: 2019-04-02 22:36:45.318000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545e0fa8fb50'
down_revision = 'ef7b0eade933'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emprestimos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('livro_id', sa.Integer(), nullable=True),
    sa.Column('data_emprestimo', sa.DateTime(), nullable=True),
    sa.Column('data_provavel_devolucao', sa.DateTime(), nullable=True),
    sa.Column('data_efetiva_devolucao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['livro_id'], ['livros.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emprestimos')
    # ### end Alembic commands ###
