"""empty message

Revision ID: ef7b0eade933
Revises: 
Create Date: 2019-04-02 21:53:10.520639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef7b0eade933'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livros',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('autor', sa.String(length=250), nullable=True),
    sa.Column('titulo', sa.String(length=250), nullable=True),
    sa.Column('isbn', sa.String(length=250), nullable=True),
    sa.Column('editora', sa.String(length=150), nullable=True),
    sa.Column('sinopse', sa.String(length=2048), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('password_hash', sa.String(length=250), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('livros')
    # ### end Alembic commands ###
